name: Test triggering workflow

on:
  workflow_dispatch:
    inputs:
      imageTags:
        description: 'Tags to push'
        required: false
        default: 'latest'

  # push:
  #   branches:
  #     - 'main'
    tags:
      - v*.*.*

jobs:
  test_action:
    name: Foo
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docker build workflow
        uses: jon-hagg/test-ci/workflow-trigger@jon/inputs
        with:
          repo: test-ci
          workflow_id: 12359014
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{"imageTags": "${{ inputs.imageTags }}"}'
