name: Test triggering workflow

on:
  workflow_dispatch:
    inputs:
      imageTags:
        description: 'Tags to push'
        required: false
        default: 'latest'

jobs:
  test_action:
    name: Foo
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docker build workflow
        uses: jenhagg/test-ci/workflow-trigger@main
        with:
          repo: test-ci
          workflow_id: 12359014
          token: ${{ secrets.CI_TOKEN_CLONE_REPO }}
          # inputs: '{"imageTags": "${{ github.event.inputs.imageTags }}"}'
