name: Publish docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - v*.*.*

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/jon-hagg/testci
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=semver,pattern={{raw}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Build and push
        if: startsWith(github.ref, 'refs/heads/main')
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/jon-hagg/testci:latest

