name: Publish docker image

on:
  workflow_dispatch:
    inputs:
      imageTags:
        description: 'Tags to push'
        required: false
        default: 'latest'

  # push:
  #   branches:
  #     - 'main'
    # tags:
    #   - v*.*.*

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: git log | head -1 > sha.txt

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/jon-hagg/testci
          # flavor: |
          #   latest=${{ github.ref == 'refs/heads/main' }}
          tags: ${{ github.event.inputs.imageTags }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}

